version: '3.8'

networks:
  app_network:
    name: app_network

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: student_db
    ports:
      - "27017:27017"
    networks:
      - app_network

  backend:
    image: priyanshu0811/backend
    #container_name: student-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app_network
  frontend:
    image: priyanshu0811/frontend

    #container_name: student-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app_network

